pipelines:
  custom:
    deploy-to-testing:
      - step:
          name: Deploy to S3
          image: node:16
          deployment: Test
          script:
            - export DOCU_VERSION=`date '+%y%m%d-%H%M'`
            - cd steve-whitepaper/site
            - npm install
            - npm run build
            - pipe: atlassian/aws-s3-deploy:0.3.7
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_REGION
                S3_BUCKET: $S3_BUCKET
                LOCAL_PATH: 'build'
                DELETE_FLAG: 'true'

